# basic options
title: All Slime
![alt test](1747e88b-d457-4d77-9c31-a91b391e0e84_200x200.png)
author: AC Slimes
description: A Blog for All Things Slime related


# Build settings
markdown: kramdown
theme: minima
